import type { Metadata } from "next"
import Link from "next/link"
import { PageFrame } from "../components/page-frame"

export const metadata: Metadata = { title: "Implement", description: "Schemas, examples and implementation-neutral guidance for VES 1.2 Draft.", alternates: { canonical: "/implement" } }
const files=[["VES Decision Envelope schema","/schemas/ves-decision-envelope-1.2-draft.schema.json"],["External Evidence Object schema","/schemas/ves-external-evidence-object-1.2-draft.schema.json"],["Qualified claims-referral envelope","/examples/claims-referral-qualified.json"],["Qualified verification result","/examples/claims-referral-qualified-result.json"]]
export default function ImplementPage(){return <PageFrame eyebrow="Implementation path" title="Build against the public exchange surface." intro="Start with the JSON Schemas and fictional test vectors. Preserve native evidence, pin versions, declare limitations and keep proprietary implementation choices outside the portable envelope." toc={[{id:"artefacts",label:"Artefacts"},{id:"path",label:"Path"},{id:"guidance",label:"Guidance"},{id:"roadmap",label:"Roadmap"}]}>
  <h2 id="artefacts">Public artefacts</h2><div className="download-list">{files.map(([label,href])=><Link key={href} className="download-link" href={href} download>{label}<span>JSON ↗</span></Link>)}</div>
  <h2 id="path">Suggested implementation path</h2><ol><li>Select and pin the applicable VES profile.</li><li>Map existing decision identifiers, context, conditions, authority and commitment fields.</li><li>Wrap native evidence with External Evidence Objects; do not rewrite source semantics.</li><li>Generate a Decision Envelope at or immediately adjacent to organisational commitment.</li><li>Retain integrity details, applicability periods, replay references and explicit limitations.</li><li>Validate the exchange structure and publish the result status for the stated profile.</li></ol>
  <h2 id="guidance">Implementation guidance</h2><div className="callout">VES does not require a database, a particular cloud, a VES-hosted API or storage of raw insurance evidence on a public website.</div><p>Use opaque references where possible. Separate public exchange semantics from internal capture orchestration. Do not place personal or confidential claim content into public test vectors.</p>
  <h2 id="roadmap">Roadmap, not current capability</h2><p>A maintained conformance test suite, adapter interface and implementation registry may follow after public review. No broad adapter support, independent verification service or conformance programme is claimed in this draft.</p>
  </PageFrame>}

