import type { Metadata } from "next"
import { PageFrame } from "../components/page-frame"

export const metadata: Metadata = { title: "Interoperability", description: "How VES preserves native external evidence inside a portable consequential decision-state.", alternates: { canonical: "/interoperability" } }
const examples=[["Runtime action records","Control receipts, signed action records, model-gateway logs and policy-enforcement records may evidence what a system did."],["Governance evidence schemas","Governance-posture evidence may inform risk pricing, underwriting or capital assessment without becoming the decision-state itself."],["Audit logs and telemetry","Logs and telemetry may evidence events, sequences and operating conditions from source systems."],["Model cards and registry records","Model documentation and version records may identify a system contribution and its declared operating context."],["Claims and underwriting records","Core insurance systems may supply claim state, risk information, transaction history and source references."],["Human review records","Approvals, overrides, referrals and rationale may evidence human judgement and authority at execution."],["External data sources","Time-bound third-party data may be referenced with its issuer, version, applicability and limitations."]]
export default function InteroperabilityPage(){return <PageFrame eyebrow="External Evidence Profile" title="Native evidence remains native." intro="VES links evidence from source systems and external standards without requiring those artefacts to be rewritten into a proprietary format." toc={[{id:"principle",label:"Principle"},{id:"wrapper",label:"Wrapper"},{id:"examples",label:"Evidence sources"},{id:"governance",label:"Governance evidence"},{id:"boundary",label:"Runtime boundary"}]}>
  <h2 id="principle">Interoperability principle</h2><p>VES does not require evidence to originate inside Veriscopic. It defines how decision-relevant evidence is linked, qualified and preserved around a consequential decision. A source object remains authoritative in its native domain, while its VES wrapper declares how it relates to the decision and how it may be assessed later.</p><p>Veriscopic publishes related implementation context about <a href="https://veriscopic.com/decision-state">decision-state</a>; VES defines the portable, implementation-neutral exchange model for preserving it.</p>
  <h2 id="wrapper">External Evidence Object wrapper</h2><p>The wrapper records an opaque evidence identifier, type, source system or standard, issuer, version, capture time, applicability period, integrity details, decision relation and known limitations. It MAY reference an object rather than embed its contents.</p>
  <h2 id="examples">Illustrative evidence sources</h2><div className="evidence-grid">{examples.map(([title,description])=><article key={title} className="evidence-card"><h3>{title}</h3><p>{description}</p></article>)}</div>
  <h2 id="governance">Governance and risk evidence</h2><p>Evidence about an organisation’s governance posture may be relevant to risk pricing, underwriting or capital assessment. VES can reference such evidence as an Evidence Object, but VES is concerned with the decision-state of a specific consequential decision, not with scoring an organisation’s overall governance maturity.</p><p>Where an organisation uses a Veriscopic <a href="https://veriscopic.com/evidence">Evidence Pack</a>, that pack may be referenced as one external Evidence Object. It does not replace the wider VES Decision Envelope or establish business authority by itself.</p>
  <h2 id="boundary">Runtime evidence and the decision boundary</h2><div className="callout callout-warning">Runtime-control receipts, model-gateway logs, signed action records and policy-enforcement records may form part of a VES Decision Envelope. They do not, by themselves, establish the full business decision-state unless linked to applicable evidence, business authority, human judgement and organisational commitment.</div><p>VES evaluates whether the wider submitted package supports the selected profile. It does not require a particular external standard.</p>
  </PageFrame>}
