import type { Metadata } from "next"
import Link from "next/link"
import { PageFrame } from "../components/page-frame"
import { coreConcepts, envelopeComponents, maturityLevels } from "@/content/standard"
import { TechnicalStructuredData } from "../components/technical-structured-data"

export const metadata: Metadata = { title: "Standard", description: "Scope, principles, vocabulary and Decision-Evidence Maturity for VES 1.2 Draft.", alternates: { canonical: "/standard" } }

export default function StandardPage() {
  return <><TechnicalStructuredData path="/standard#core-concepts" title="The Verifiable Evidence Standard" description="Scope, principles, defined vocabulary and Decision-Evidence Maturity for VES 1.2 Draft." terms={coreConcepts.map(({term,definition})=>({name:term,description:definition}))}/><PageFrame eyebrow="Canonical overview" title="The standard" intro="VES defines a portable decision envelope for preserving the evidence, authority, conditions, system contribution and human judgement behind a consequential organisational commitment." toc={[{id:"scope",label:"Scope"},{id:"principles",label:"Principles"},{id:"core-concepts",label:"Core concepts"},{id:"model",label:"Public model"},{id:"maturity",label:"Maturity"},{id:"exclusions",label:"Exclusions"}]}>
    <div className="callout">VES 1.2 is a draft publication. It is intended for implementation review and does not represent a conformance certification programme.</div>
    <h2 id="scope">Scope</h2><p>VES applies to consequential decisions that may later require independent review. In insurance this includes claims, underwriting, delegated authority, referrals, settlements, reserves and renewals. Decisions may be human, rules-based, workflow-driven, AI-assisted, or combinations of these.</p><p>The standard addresses the evidence package around a decision. It does not prescribe how organisations reach decisions or require a particular technology, storage architecture or operating model.</p>
    <h2 id="principles">Principles</h2><ul><li><strong>Point-in-time:</strong> applicability is assessed against the conditions in force when the organisation committed.</li><li><strong>Portable:</strong> evidence references can move beyond the originating workflow without losing declared meaning.</li><li><strong>Implementation-neutral:</strong> native evidence remains native and may originate in any conforming source.</li><li><strong>Independently reviewable:</strong> the package describes how another party can assess it later.</li><li><strong>Transparent qualification:</strong> limitations and indeterminate facts remain visible.</li></ul>
    <h2 id="core-concepts">Core concepts</h2><p>A shared vocabulary for preserving, checking and later understanding consequential decisions without reconstructing them from fragmented systems.</p><div className="callout"><strong>Foundational distinction</strong><p>Most systems can describe a decision after the event. VES concerns whether the material evidence, authority and governing conditions relevant to that decision were preserved in a form that can be checked later.</p><p>A recorded action is not necessarily an explainable decision.</p></div><dl className="core-concepts">{coreConcepts.map((concept)=><div id={concept.id} key={concept.id}><dt>{concept.term}</dt><dd>{concept.definition}</dd></div>)}</dl>
    <h2 id="model">Public model</h2><div className="definition-grid">{envelopeComponents.map((item)=><article key={item.key} className="definition-card"><span>{item.key}</span><h3>{item.title}</h3><p>{item.description}</p></article>)}</div><p>The field-level model and normative requirement language are published in the <Link href="/specification">technical specification</Link>.</p>
    <h2 id="maturity">Decision-Evidence Maturity</h2><div className="definition-grid">{maturityLevels.map(([level,title,description])=><article key={level} className="definition-card"><span>{level}</span><h3>{title}</h3><p>{description}</p></article>)}</div>
    <h2 id="exclusions">What VES does not establish</h2><p>VES is not generic AI governance, a runtime control gateway, a model registry, an audit log, a system of record, a certification programme, or a guarantee that a decision is correct, lawful, fair or compliant. A verification result applies only to the submitted evidence package and stated profile.</p><ul><li>VES does not establish that every relevant action or source artefact was captured.</li><li>VES does not establish that the underlying contents of an Evidence Object are factually correct; it records how that object was declared, linked and assessed within the Decision Envelope.</li></ul>
  </PageFrame></>
}
